### PR TITLE
Create Rozier cipher

### LINKED ISSUE #22: Introduce Rozier Cypher
#### Feature Request:
It would be nice to have a cypher algorithm like Rozier in ENCODN

#### Solution required:
1. Add a .py file with the named **ROZIER.py** and add a function definition by the name **encrypt(String)** that takes in a plaintext string as input and returns the encrypted string.
2. In ROZIER..py add another function definition by the name **decrypt(String)** that takes in an encypted string and returns the plaintext string corresponding to it. Return "The entered hash/cypher/value is incorrect!!!" in case of discrepancies.

#### Additional Info:
The file should be stored in the **ENCODN/ENCODN/TOOLS/CRYPTOGRAPHY/OTHER/ROZIER/** directory only, the filename, function name should be as specified above (case sensitive).

### PR DESCRIPTION
**Pull request by MrLukeKR**

### CODE REVIEW

**Comment by MrLukeKR** [comment]
Please can this be labelled accordingly with the necessary Hacktoberfest labels (hacktoberfest-accepted etc.) :)

**Comment by MrLukeKR** [comment]
And link to: https://github.com/DSC-IIIT-Kalyani/ENCODN/issues/22 :)

**Comment by akshitadixit** [comment]
Very well documented! Thank you for the contribution. Please feel free to create new issues if you wish to pickup any other algorithm from [dcode.fr](https://dcode.fr/en)

**Comment by MrLukeKR** [comment]
> Very well documented! Thank you for the contribution. Please feel free to create new issues if you wish to pickup any other algorithm from [dcode.fr](https://dcode.fr/en)

Thanks very much! I'll most definitely do some more algorithms for you :)

**Pull request merged**
