### PR TITLE
hashed values

### LINKED ISSUE #21: Introduce MD4 encryption-decryption algorithm
#### Feature Request:
It would be nice to have a hashing algorithm like MD4 in ENCODN

#### Solution required:
1. Add a .py file with the named **MD4.py** and add a function definition by the name **encrypt(String)** that takes in a plaintext string as input and returns the MD4 encrypted string.
2. In MD4.py add another function definition by the name **decrypt(String)** that takes in a MD4 encypted string and returns the plaintext string corresponding to it. Return "The entered hash/cypher/value is incorrect!!!" in case of discrepancies.

#### Additional Info:
The file should be stored in the **ENCODN/ENCODN/TOOLS/CRYPTOGRAPHY/MODERN CRYPTOGRAPHY/MD4/** directory only, the filename, function name should be as specified above (case sensitive).

### PR DESCRIPTION
**Pull request by rexdivakar**

### CODE REVIEW

**Comment by rexdivakar** [comment]
#21 Completed, please validate and approve the PR @akshitadixit

**Comment by akshitadixit** [comment]
Kindly read the issue once again. The file directory isn't correct. Also the function names aren't set properly.

**Comment by rexdivakar** [comment]
Hi @akshitadixit  i seriously believe u have confused with encryption and hashing, but i have altered my code as per ur needs. Please check again

**Review by rexdivakar — COMMENTED** [review]
updated changes

**Comment by akshitadixit** [comment]
> Hi @akshitadixit i seriously believe u have confused with encryption and hashing, but i have altered my code as per ur needs. Please check again

Sir I'm clear about my concepts, but since [dcode.fr](https://dcode.fr/en) categorises MD4 under cryptography, we need to set similar standards for the repository. 

 However thank you for the contribution :) feel free to pick up any other algorithm from the website!

**Comment by akshitadixit** [comment]
> Hi @akshitadixit i seriously believe u have confused with encryption and hashing, but i have altered my code as per ur needs. Please check again

Sir I'm clear about my concepts, but since [dcode.fr](https://dcode.fr/en) categorises MD4 under cryptography, we need to set similar standards for the repository. 

 However thank you for the contribution :) feel free to pick up any other algorithm from the website!

**Pull request merged**
